[pytest]

testpaths =
    tests

markers =
    smoke: smoke tests
    regression: regression tests
    api: api tests
    e2e: end to end tests

addopts =
    --browser chromium
    --browser firefox
    --browser webkit
